name: Blog CI/CD

on:
  push:
    branches:
      - main  # 只在main上push触发部署
    paths-ignore:   # 下列文件的变更不触发部署
      - README.md
      - LICENSE
        
jobs:
  
  build-production:
  
    runs-on: ubuntu-latest            # 使用ubuntu系统镜像运行自动化脚本
    
    steps:  # 自动化步骤
      - name: Installing node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/checkout@v2     # 第一步，检出仓库副本
      
      - name: Install dependencies    # 第二步，安装依赖
        run: npm install

      - name: Build                   # 第三步，打包代码
        run: npm run build --if-present

      - name: Deploy to Server        # 第四步，rsync推送文件
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: /root/blog/dist/

      
